generator:
  class:                         sfPropelMooDooGenerator
  param:
    model_class:                 sfGuardPermission
    theme:                       mooDooAdmin
    non_verbose_templates:       true
    with_show:                   false
    singular:                    ~
    plural:                      ~
    route_prefix:                sf_guard_permission
    with_propel_route:           1

    config:
      list:
        title:                   Permission list
        display:                 [name, description]

        actions:
          new:                   { label: Nueva, inWinPopUp:true }
          
        object_actions:
          _edit:                  { label: Edit, inWinPopUp:true }
          _delete:               ~

        

      edit:
        title: Editing Permission "%%name%%"

      new:
        title: New Permission
